[project]
name = "themed-print"
authors = [{name = "Yiheng-Yu", email = "yuyiheng1994@gmail.com"}]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "rich >= 14.0.0",
    "requests"
]

[project.optional-dependencies]
dev = [
    "pytest"
]
